### ISSUE TITLE
Return value of SnowflakeValueOperator

### ISSUE THREAD

**Issue by cklat** [astronomer/airflow-data-quality-demo#22]
Hi There!

I have a question related to the use of the SnowflakeOperators especially the use of the SnowflakeValueOperator. It's not necessarily related to your astronomer SDK but unfortunately I don't find any other information regarding the use of the SnowflakeOperator on Google. So I hope you might help me out. Would really appreciate it! 

When I'm trying to use the SnowflakeValueOperator in a DAG for my use case like you did in the Taxi Example https://github.com/astronomer/airflow-data-quality-demo/blob/830f35afaab01cbf62474ce0222405bfc5ecc311/dags/snowflake_examples/taxi_snowflake.py#L136 the execution fails for me. I get an error like this: `airflow.exceptions.AirflowException: Converting a result to float failed.`

This is because I probably get a JSON object returned by Snowflake which probably is not what the SnowflakeValueOperators expects.
The return value of the response looks like this:
```
Results:
{'COUNT(*)': 100}  
```
and I'm not sure how to access the COUNT(*) key through the SnowflakeValueOperator.

Is there a setting to tell the SnowflakeOperators, or maybe in airflow in general, how to return the values queried by the operators?

Thanks a lot!

**Comment by denimalpaca** [comment]
Hey @cklat , sorry for the late response here. There was a recent change in the way the Snowflake hook returned values, switching from the way other dbapi hooks were returning values (via a set) to a dictionary. This broke quite a lot of things, including all the `Snowflake.*CheckOperators`. I believe there has since been a fix, though there is no way to directly change the value as of now I believe. See these issues for more details:
https://github.com/apache/airflow/issues/27976
https://github.com/apache/airflow/pull/27997
